name: Build PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: python-version: 3.12
    - run: pip install mkdocs mkdocs-material pandoc weasyprint
    - run: mkdocs build -f mkdocs.yml
    - run: |
        weasyprint site/index.html guia-tocantins.pdf --optimize-images
    - uses: actions/upload-artifact@v4
      with:
        name: guia-pdf
        path: guia-tocantins.pdf
